#ifndef __CONFIG_H__
#define __CONFIG_H__

//#define DEBUG_TENSORS
// #define DEBUG_TOKENS

#define CONFIG_ENABLE_AVX2
#define CONFIG_USE_THREADS	1

#define MAX_PROMPT_BATCH_SIZE 1024
#define MAX_THREADS 32
#define MAX_TASKS 256

#define TOOL_CALL_BUFFER_SIZE 1024

#endif
